[2025-08-07 14:32:22,060: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-07 14:32:22,065: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-07 14:32:22,067: INFO: common: created directory at: artifacts]
[2025-08-07 14:32:22,070: INFO: common: created directory at: artifiacts/data_ingestion]
[2025-08-07 14:34:17,821: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-07 14:34:17,828: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-07 14:34:17,830: INFO: common: created directory at: artifacts]
[2025-08-07 14:34:17,833: INFO: common: created directory at: artifiacts/data_ingestion]
[2025-08-07 14:38:48,811: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-07 14:38:48,811: ERROR: main: name 'ConfigurationManager' is not defined]
Traceback (most recent call last):
  File "C:\Users\sunil kumar\OneDrive - AlgoDox Technology PVT LTD\Desktop\dl_ops_champios\vinipro\main.py", line 13, in <module>
    data_ingestion.main()
  File "C:\Users\sunil kumar\OneDrive - AlgoDox Technology PVT LTD\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 14, in main
    config = ConfigurationManager()
            ^^^^^^^^^^^^^^^^^^^^
NameError: name 'ConfigurationManager' is not defined
[2025-08-07 14:40:46,960: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-07 14:40:46,961: ERROR: main: name 'ConfigurationManager' is not defined]
Traceback (most recent call last):
  File "C:\Users\sunil kumar\OneDrive - AlgoDox Technology PVT LTD\Desktop\dl_ops_champios\vinipro\main.py", line 13, in <module>
    data_ingestion.main()
  File "C:\Users\sunil kumar\OneDrive - AlgoDox Technology PVT LTD\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 14, in main
    config = ConfigurationManager()
            ^^^^^^^^^^^^^^^^^^^^
NameError: name 'ConfigurationManager' is not defined
[2025-08-07 14:43:19,653: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-07 14:43:19,654: ERROR: main: name 'ConfigurationManager' is not defined]
Traceback (most recent call last):
  File "C:\Users\sunil kumar\OneDrive - AlgoDox Technology PVT LTD\Desktop\dl_ops_champios\vinipro\main.py", line 13, in <module>
    data_ingestion.main()
  File "C:\Users\sunil kumar\OneDrive - AlgoDox Technology PVT LTD\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    config = ConfigurationManager()
            ^^^^^^^^^^^^^^^^^^^^
NameError: name 'ConfigurationManager' is not defined
[2025-08-07 14:44:22,410: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-07 14:44:22,413: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-07 14:44:22,420: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-07 14:44:22,423: INFO: common: created directory at: artifacts]
[2025-08-07 14:44:22,424: INFO: common: created directory at: artifiacts/data_ingestion]
[2025-08-07 14:44:23,226: ERROR: main: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\data.zip']
Traceback (most recent call last):
  File "C:\Users\sunil kumar\OneDrive - AlgoDox Technology PVT LTD\Desktop\dl_ops_champios\vinipro\main.py", line 13, in <module>
    data_ingestion.main()
  File "C:\Users\sunil kumar\OneDrive - AlgoDox Technology PVT LTD\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.download_file()
  File "C:\Users\sunil kumar\OneDrive - AlgoDox Technology PVT LTD\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\components\data_ingestion.py", line 18, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunil kumar\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 250, in urlretrieve
    tfp = open(filename, 'wb')
          ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\data.zip'
[2025-08-07 14:45:28,280: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-07 14:45:28,286: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-07 14:45:28,290: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-07 14:45:28,293: INFO: common: created directory at: artifacts]
[2025-08-07 14:45:28,296: INFO: common: created directory at: artifiacts/data_ingestion]
[2025-08-07 14:45:28,606: ERROR: main: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\data.zip']
Traceback (most recent call last):
  File "C:\Users\sunil kumar\OneDrive - AlgoDox Technology PVT LTD\Desktop\dl_ops_champios\vinipro\main.py", line 13, in <module>
    data_ingestion.main()
  File "C:\Users\sunil kumar\OneDrive - AlgoDox Technology PVT LTD\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.download_file()
  File "C:\Users\sunil kumar\OneDrive - AlgoDox Technology PVT LTD\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\components\data_ingestion.py", line 18, in download_file
    filename, headers = request.urlretrieve(
                        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunil kumar\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 250, in urlretrieve
    tfp = open(filename, 'wb')
          ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\data.zip'
[2025-08-07 14:47:38,672: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-07 14:47:38,680: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-07 14:47:38,685: INFO: common: created directory at: artifacts]
[2025-08-07 14:47:38,688: INFO: common: created directory at: artifiacts/data_ingestion]
[2025-08-07 14:56:43,731: INFO: 3399376260: artifacts/data_ingestion/data.zip download! with following info: 
 Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: CF7B:51A30:23A34B:574EE6:68946BD3
Accept-Ranges: bytes
Date: Thu, 07 Aug 2025 09:26:41 GMT
Via: 1.1 varnish
X-Served-By: cache-bom-vanm7210054-BOM
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1754558801.192582,VS0,VE219
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: a1343ecb0050028665f7fb4da8294943d7aad4f4
Expires: Thu, 07 Aug 2025 09:31:41 GMT
Source-Age: 0

]
[2025-08-07 14:57:24,501: INFO: 3399376260: File already exists of size: ~ 11345 KB]
[2025-08-07 14:57:40,550: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-07 14:57:40,556: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-07 14:57:40,559: INFO: common: created directory at: artifacts]
[2025-08-07 14:57:40,561: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-07 14:57:40,563: INFO: 3399376260: File already exists of size: ~ 11345 KB]
[2025-08-07 14:58:12,041: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-07 14:58:12,044: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-07 14:58:12,046: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-07 14:58:12,048: INFO: common: created directory at: artifacts]
[2025-08-07 14:58:12,049: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-07 14:58:12,050: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-08-07 14:58:12,648: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-08-13 17:00:07,379: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-13 17:00:07,407: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-13 17:00:07,409: INFO: common: created directory at: artifacts]
[2025-08-13 17:00:07,411: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-13 17:00:23,411: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-13 17:00:23,779: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-13 17:01:32,496: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-13 17:01:32,524: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-13 17:01:32,530: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-13 17:01:32,531: INFO: common: created directory at: artifacts]
[2025-08-13 17:01:32,532: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-13 17:01:32,532: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-08-13 17:01:33,163: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-08-13 17:01:33,163: INFO: main: >>>>>> Prepare Base Model started <<<<]
[2025-08-13 17:01:33,165: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-13 17:01:33,167: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-13 17:01:33,168: INFO: common: created directory at: artifacts]
[2025-08-13 17:01:33,168: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-13 17:01:33,927: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-13 17:01:34,399: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-13 17:01:34,917: INFO: main: >>>>>>> Prepare Base Model completed <<<<<

x=======x]
[2025-08-17 09:36:34,070: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-17 09:36:34,094: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-17 09:36:34,099: INFO: common: created directory at: artifacts]
[2025-08-17 09:39:51,652: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-17 09:39:51,657: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-17 09:39:51,660: INFO: common: created directory at: artifacts]
[2025-08-17 10:04:17,309: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-17 10:04:17,314: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-17 10:04:17,317: INFO: common: created directory at: artifacts]
[2025-08-17 10:05:06,692: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-17 10:05:06,699: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-17 10:05:06,701: INFO: common: created directory at: artifacts]
[2025-08-18 13:32:42,470: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-18 13:32:42,494: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-18 13:32:42,497: INFO: common: created directory at: artifacts]
[2025-08-18 15:03:41,893: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-18 15:03:41,900: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-18 15:03:41,902: INFO: common: created directory at: artifacts]
[2025-08-18 15:03:41,906: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-18 15:03:41,909: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-22 15:27:43,823: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-22 15:27:43,846: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-22 15:27:43,848: INFO: common: created directory at: artifacts]
[2025-08-22 15:27:43,851: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-22 15:27:43,854: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-22 15:32:36,341: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-22 15:32:36,346: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-22 15:32:36,348: INFO: common: created directory at: artifacts]
[2025-08-22 15:32:36,350: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-22 15:32:36,352: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-22 15:33:37,321: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-22 15:33:37,327: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-22 15:33:37,330: INFO: common: created directory at: artifacts]
[2025-08-22 15:33:37,333: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-22 15:33:37,335: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-22 16:10:12,249: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-22 16:10:12,253: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-22 16:10:12,259: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-22 16:10:12,261: INFO: common: created directory at: artifacts]
[2025-08-22 16:10:12,261: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-22 16:10:12,262: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-08-22 16:10:13,013: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-08-22 16:10:13,014: INFO: main: >>>>>> Prepare Base Model started <<<<]
[2025-08-22 16:10:13,020: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-22 16:10:13,024: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-22 16:10:13,028: INFO: common: created directory at: artifacts]
[2025-08-22 16:10:13,030: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-22 16:10:14,016: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-22 16:10:14,262: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-22 16:10:18,967: INFO: main: >>>>>>> Prepare Base Model completed <<<<<

x=======x]
[2025-08-22 16:10:18,969: INFO: main: >>>>>> Training started <<<<<<]
[2025-08-22 16:10:18,979: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-22 16:10:18,989: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-22 16:10:18,991: INFO: common: created directory at: artifacts]
[2025-08-22 16:10:18,993: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-22 16:10:18,994: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-22 16:10:19,128: ERROR: main: "'training'"]
Traceback (most recent call last):
  File "box\\box.py", line 594, in box.box.Box.__getitem__
KeyError: 'training'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sunil kumar\OneDrive - AlgoDox Technology PVT LTD\Desktop\dl_ops_champios\vinipro\main.py", line 37, in <module>
    model_trainer.main()
  File "C:\Users\sunil kumar\OneDrive - AlgoDox Technology PVT LTD\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\pipeline\stage_03_training.py", line 21, in main
    training_config = config.get_training_config()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunil kumar\OneDrive - AlgoDox Technology PVT LTD\Desktop\dl_ops_champios\vinipro\src\cnnClassifier\config\configuration.py", line 68, in get_training_config
    training = self.config['training']
               ~~~~~~~~~~~^^^^^^^^^^^^
  File "box\\box.py", line 621, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'training'"
[2025-08-23 09:13:57,053: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-23 09:13:57,072: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-23 09:13:57,074: INFO: common: created directory at: artifacts]
[2025-08-23 09:13:57,076: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-23 09:13:57,079: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-27 20:13:24,819: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-27 20:13:24,851: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-27 20:13:24,855: INFO: common: created directory at: artifacts]
[2025-08-27 20:13:24,864: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-27 20:13:24,869: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-28 11:57:05,646: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-28 11:57:05,662: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-28 11:57:05,663: INFO: common: created directory at: artifacts]
[2025-08-28 11:57:05,665: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-28 11:57:05,668: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-28 17:03:58,024: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-28 17:03:58,038: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-28 17:03:58,040: INFO: common: created directory at: artifacts]
[2025-08-28 17:04:49,133: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-28 17:04:49,139: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-28 17:04:49,141: INFO: common: created directory at: artifacts]
[2025-08-28 17:04:49,144: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-28 17:04:49,149: INFO: 1951570136: File already exists of size: ~ 11345 KB]
[2025-08-28 17:22:17,789: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-08-28 17:22:17,800: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-28 17:22:17,809: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-28 17:22:17,810: INFO: common: created directory at: artifacts]
[2025-08-28 17:22:17,811: INFO: common: created directory at: artifacts/data_ingestion]
[2025-08-28 17:22:17,812: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-08-28 17:22:19,178: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-08-28 17:22:19,203: INFO: main: >>>>>> Prepare Base Model started <<<<]
[2025-08-28 17:22:19,230: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-28 17:22:19,248: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-28 17:22:19,249: INFO: common: created directory at: artifacts]
[2025-08-28 17:22:19,252: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-08-28 17:22:22,397: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-28 17:22:23,376: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-28 17:22:23,591: INFO: main: >>>>>>> Prepare Base Model completed <<<<<

x=======x]
[2025-08-28 17:22:23,594: INFO: main: >>>>>> Training started <<<<<<]
[2025-08-28 17:22:23,620: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-28 17:22:23,635: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-28 17:22:23,638: INFO: common: created directory at: artifacts]
[2025-08-28 17:22:23,640: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-28 17:22:23,653: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-28 17:22:23,659: INFO: common: created directory at: artifacts\training]
[2025-08-28 17:22:23,986: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-28 17:29:11,108: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-28 17:29:11,370: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-28 17:29:11,495: INFO: main: >>>>>> Training completed <<<<<<

x==========x]
[2025-08-28 17:29:11,496: INFO: main: >>>>>> Evaluation started <<<<<<]
[2025-08-28 17:29:11,508: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-28 17:29:11,515: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-28 17:29:11,519: INFO: common: created directory at: artifacts]
[2025-08-28 17:29:12,002: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-08-28 17:29:45,264: INFO: common: json file saved at: scores.json]
[2025-08-28 17:29:45,265: INFO: main: >>>>>> Evaluation completed <<<<<<

x==========x]
[2025-08-28 17:33:36,762: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-08-28 17:33:36,768: INFO: common: YAML file params.yaml loaded successfully]
[2025-08-28 17:33:36,770: INFO: common: created directory at: artifacts]
[2025-08-28 17:33:36,773: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-08-28 17:33:36,775: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-08-28 17:33:36,781: INFO: common: created directory at: artifacts\training]
[2025-08-28 17:42:33,935: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-08-28 17:42:34,226: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
